# Generated by Django 3.1.1 on 2020-09-23 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('computers', models.BooleanField()),
                ('projector', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lessons_count', models.IntegerField()),
                ('computers', models.BooleanField()),
                ('projector', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('student_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('tr', 'Teacher'), ('sf', 'Staff'), ('gt', 'Guest')], default='gt', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditories', models.ManyToManyField(related_name='wishes', to='schedual_app.Auditory')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='schedual_app.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='schedual_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='groups',
            field=models.ManyToManyField(related_name='disciplines', to='schedual_app.Group'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(related_name='disciplines', to='schedual_app.Profile'),
        ),
    ]
