# Generated by Django 3.1.1 on 2020-09-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedual_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=200)),
                ('staff_credentials', models.BooleanField(default=False)),
                ('teacher_credentials', models.BooleanField(default=False)),
                ('guest_credentials', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedualProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role_name',
        ),
        migrations.AddField(
            model_name='group',
            name='division',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedual_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='schedual_app.schedualproject'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedual_app.role'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teachers',
            field=models.ManyToManyField(related_name='disciplines', to='schedual_app.Teacher'),
        ),
    ]
