# Generated by Django 3.1.1 on 2020-09-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedual_app', '0002_auto_20200923_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='fifth_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='first_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='fourth_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='second_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='seventh_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='sixth_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='third_lesson',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedual_app.profile'),
        ),
    ]
