# Generated by Django 3.1.1 on 2020-10-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedual_app', '0005_auto_20200926_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditory',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditories', to='schedual_app.schedualproject'),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schedual_app.schedualproject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='schedual_app.schedualproject'),
        ),
        migrations.AddField(
            model_name='wish',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='schedual_app.schedualproject'),
        ),
    ]
