# Generated by Django 3.1.1 on 2020-10-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedual_app', '0006_auto_20201001_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedual_app.role'),
        ),
    ]
