# Generated by Django 3.1.1 on 2020-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedual', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role_name',
            field=models.CharField(choices=[('tr', 'Teacher'), ('sf', 'Staff'), ('gt', 'Guest')], default='gt', max_length=2),
        ),
    ]
